apiVersion: v1
kind: Service
metadata: 
  name: terraform-service
spec:
  selector:
    app: terraform
  type: NodePort
  ports: 
    - protocol: TCP
      port: 5000
      targetPort: 3001
      nodePort: 31111
